// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import fullcalendar_controller from "./fullcalendar_controller"
application.register("fullcalendar", fullcalendar_controller)

import edit_firm_controller from "./edit_firm_controller"
application.register("edit-firm", edit_firm_controller)

import edit_therapist_controller from "./edit_therapist_controller"
application.register("edit-therapist", edit_therapist_controller)
