// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import fullcalendar_controller from "./fullcalendar_controller"
application.register("fullcalendar", fullcalendar_controller)

import edit_form_controller from "./edit_form_controller"
application.register("edit-form", edit_form_controller)

import booking_controller from "./booking_controller"
application.register("booking", booking_controller)

import slots_calendar_controller from "./slots_calendar_controller"
application.register("slots-calendar", slots_calendar_controller)
